Add vue viewer
pykafe/timorGIS pull request #228
Opened 2021-07-28 03:10 UTC by eraulo

Closes #no

## Description of the Problem / Feature
-  
## Explanation of the solution
- Added vue viewer.

## Instructions on making this work
- npm install
- ./manage.py runserver

2021-07-28 13:24 UTC, marobo commented
I think we don't need zoom button, we can make it by just click on the image.

2021-07-28 13:27 UTC, marobo requested changes

2021-07-28 13:27 UTC, marobo commented on src/components/PhotoTimor.vue
> +                        <button type="button" class="btn-outline-success" @click="selectImgObject(image.image)">Zoom</button>
I think we don't need zoom button, we can make it by just click on the image.

2021-07-28 13:27 UTC, marobo commented on src/components/PhotoTimor.vue
> +                        rotatable: false,
Have a rotatable icon button not working...

2021-08-06 11:08 UTC, eraulo commented on src/components/PhotoTimor.vue
> +                        rotatable: false,
This isn't rotatable icon only have prev button, next button and reset button.

2021-08-06 13:33 UTC, marobo commented on src/components/PhotoTimor.vue
> +                        rotatable: false,
![Uploading Screen Shot 2021-08-06 at 22.31.50.png…]()

2021-08-06 13:34 UTC, marobo commented on src/components/PhotoTimor.vue
> +                        rotatable: false,
<img width="296" alt="Screen Shot 2021-08-06 at 22 31 50" src="https://user-images.githubusercontent.com/12780301/128518421-e6b559be-9bf9-4adb-bc09-9c9b3b876f2d.png">

2021-08-28 00:34 UTC, marobo commented
Error when I ran `npm run watch` in this branch!

2021-08-28 00:46 UTC, marobo commented
> @eraulo , Error when I ran `npm run watch` in this branch!

Forgot to do `npm install`, Working fine now!

2021-08-28 00:46 UTC, marobo approved these changes

2021-08-28 00:50 UTC, merged