Displaying loading and sorry
pykafe/timorGIS pull request #232
Opened 2021-08-28 01:24 UTC by eraulo

Closes #issue_number

## Description of the Problem / Feature
- 
## Explanation of the solution
- [ ] 

## Instructions on making this work
-

2021-08-28 01:39 UTC, PeteCoward approved these changes

2021-08-31 13:04 UTC, marobo requested changes

2021-09-04 00:28 UTC, PeteCoward commented on src/components/PhotoTimor.vue
> +    top: 0px;
```suggestion
    top: 0px;
    left: 0px;
```

2021-09-04 00:48 UTC, marobo approved these changes

2021-09-04 00:48 UTC, merged