Date range validation
pykafe/timorGIS pull request #243
Opened 2021-09-04 00:45 UTC by joanico

Closes #issue_number

## validate for End date must be greater than start date
- 
## Explanation of the solution

## Instructions on making this work
-

2021-09-04 01:17 UTC, PeteCoward commented on src/components/AddIstoria.vue
> +        name: "Submited",
```suggestion
```

????

2021-09-04 01:19 UTC, PeteCoward commented on src/components/AddIstoria.vue
>              <form v-if="amILoggedIn === true" @submit.prevent="submitNewJourney" >
```suggestion
            <form v-if="amILoggedIn === true" @submit.prevent="validateAndSubmitNewJourney" >
```

2021-09-04 01:19 UTC, PeteCoward commented on src/components/AddIstoria.vue
> +            submitNewJourney(e){
```suggestion
            validateAndSubmitNewJourney(e){
```

2021-09-04 01:20 UTC, PeteCoward commented on src/components/AddIstoria.vue
> +                e.preventDefault()
```suggestion
                if ( this.error.length === 0 ) {
                    this.submitNewJourney(e);
                }
```

2021-09-04 02:12 UTC, eraulo commented on src/components/AddIstoria.vue
> +                error:[],
```suggestion
                error:"",
```

2021-09-04 02:14 UTC, eraulo commented on src/components/AddIstoria.vue
> +                this.error=[];
```suggestion
```

2021-09-04 02:16 UTC, eraulo commented on src/components/AddIstoria.vue
> +                            </ul>
```suggestion
<p>{{ error }}</p>
                              
```

2021-09-04 02:18 UTC, eraulo commented on src/components/AddIstoria.vue
> +                    this.error.push("End date must be greater than start date")
```suggestion
                    this.error += "End date must be greater than start date"
```

2021-09-30 11:18 UTC, joanico commented on src/components/AddIstoria.vue
> +                    this.error.push("End date must be greater than start date")
@eraulo if I change according to your suggestion the result is as follows:
<img width="1424" alt="Screen Shot 2021-09-30 at 8 04 49 PM" src="https://user-images.githubusercontent.com/12932898/135445777-95e02f43-ca94-41df-aa14-d05def8f95e1.png">

2021-10-02 00:28 UTC, PeteCoward commented on src/components/AddIstoria.vue
> +                        <p v-if="error.length" style="color: red;">
```suggestion
                        <p v-if="errors.length" style="color: red;">
```

2021-10-02 00:29 UTC, PeteCoward commented on src/components/AddIstoria.vue
> +                                <li v-for="e in error" v-bind:key="e.id">
```suggestion
                                <li v-for="e in errors" v-bind:key="e.id">
```

2021-10-02 00:29 UTC, PeteCoward commented on src/components/AddIstoria.vue
> +                error:[],
```suggestion
                errors: [],
```

2021-10-02 00:30 UTC, PeteCoward commented on src/components/AddIstoria.vue
> +                this.error=[];
```suggestion
                this.errors = [];
```

2021-10-02 00:30 UTC, PeteCoward commented on src/components/AddIstoria.vue
> +                }
maybe remove this code?

2021-10-02 00:35 UTC, PeteCoward commented on src/components/AddIstoria.vue
> +                if( this.error.length === 0 ) {
```suggestion
                if( this.errors.length === 0 ) {
```

2021-10-02 00:35 UTC, PeteCoward commented on src/components/AddIstoria.vue
> +                    this.error.push("End date must be greater than start date")
```suggestion
                    this.errors.push("End date must be greater than start date")
```

2021-10-02 00:38 UTC, PeteCoward requested changes
please rename error to errors, and `git merge origin/master`

2021-10-09 00:35 UTC, PeteCoward approved these changes

2021-10-09 00:35 UTC, merged