Interface for user add comment to TimorJourney
pykafe/timorGIS pull request #246
Opened 2021-09-10 04:10 UTC by eraulo

Closes #no

## Description of the Problem / Feature
- User doesn't have comment to TimorJourney
## Explanation of the solution
- [ ] User can add a comment to TimorJourney

## Instructions on making this work
- npm run build
-./manage.py runserver

2021-09-10 13:59 UTC, marobo commented
Decision team needed!

2021-09-11 01:13 UTC, eraulo commented
> Decision team needed!

This decision in here https://docs.google.com/presentation/d/14EWwQ-4xXo9PuZCwDFADdyW6I2vnK4zafvAbuiyankU/edit#slide=id.ge838c51280_0_68

2021-09-11 01:14 UTC, PeteCoward commented on map/models.py
> +class CommentViazen(models.Model):
CommentViazen or CommentPhoto?

2021-09-11 01:22 UTC, PeteCoward commented on map/models.py
> +class CommentViazen(models.Model):
Comment?

2021-09-11 01:25 UTC, PeteCoward commented on map/models.py
> +    phototimor = models.ForeignKey(PhotoTimor, verbose_name=_('comment'), related_name="comment", on_delete=models.CASCADE)
related name
```suggestion
    phototimor = models.ForeignKey(PhotoTimor, verbose_name=_('Comment'), related_name="comments", on_delete=models.CASCADE)
```

2021-09-11 01:43 UTC, PeteCoward commented on map/models.py
> +    usercomment = models.ForeignKey(User, verbose_name=_('user'), blank=True, null=True, related_name='%(class)s_comments', on_delete=models.SET_NULL)
```suggestion
    user = models.ForeignKey(User, verbose_name=_('user'), blank=True, null=True, related_name='%(class)s_comments', on_delete=models.SET_NULL)
```

2021-09-11 01:44 UTC, PeteCoward commented on map/models.py
> +    comment = models.TextField(_('comment'), max_length=COMMENT_MAX_LENGTH)
```suggestion
    comment = models.TextField(_('Comment'), max_length=COMMENT_MAX_LENGTH)
```

2021-09-11 01:46 UTC, PeteCoward commented on map/models.py
> +    submit_at = models.DateTimeField(null=False, blank=False, default=None, db_index=True)
```suggestion
    submit_at = models.DateTimeField(auto_now_add=True, db_index=True)
```

2021-09-11 01:52 UTC, PeteCoward commented on map/models.py
> +        #abstract = True
```suggestion
```

2021-09-11 02:11 UTC, PeteCoward commented on map/models.py
> +    def save(self, *args, **kwargs):
you don't need this if you have submit_at as auto_now_add

2021-10-02 00:51 UTC, PeteCoward commented on map/models.py
> +    phototimor = models.ForeignKey(PhotoTimor, verbose_name=_('PhotoTimor'), related_name="comment", on_delete=models.CASCADE)
```suggestion
    phototimor = models.ForeignKey(PhotoTimor, verbose_name=_('PhotoTimor'), related_name="comments", on_delete=models.CASCADE)
```

2021-10-02 01:00 UTC, PeteCoward commented on map/models.py
> +        permissions = [("can_moderate", "Can moderate comments")]
we probably don't need this line unless it is used?

2021-10-02 01:06 UTC, PeteCoward commented on src/components/PhotoTimor.vue
> +                            <h4 class="modal-title" id="gridSystemModalLabel">Ilha Jaco</h4>
Which field goes here?

2021-10-02 01:08 UTC, PeteCoward commented on src/components/PhotoTimor.vue
> +                                            <img v-bind:src="selectedImageSrc" class="size_images"/>
we need to find a way to display this image aaLWAYS at the same ratio it was taken at

2021-10-02 01:11 UTC, PeteCoward commented on src/components/PhotoTimor.vue
> +    width: 100%;
To avoid squashing or stretching an image, is to only set one of height and width, not both

2021-10-02 01:18 UTC, MarioAP commented on src/components/PhotoTimor.vue
> +                <p>Add comment</p>
Add comment labele fo sai iha pajinha dahuluk kada foto sira, comment fosai pajinha hare detaillu

2021-10-02 01:48 UTC, PeteCoward commented on map/models.py
> +            "user" : {
unless we are using this info, it might be bets to just return the photo timor id, not the whole photo timor json

2021-10-02 01:51 UTC, PeteCoward commented on src/Store.js
> +                    location.reload(true)
WE should not reload the page here. There is a better way

2021-11-13 00:50 UTC, PeteCoward commented on src/Store.js
> +            setAddIstoriaError(state, payload) {
I do not understand why this is here? This PR should not be changing things to do with adding istoria

2021-11-13 00:55 UTC, PeteCoward commented on src/components/Istoria.vue
> +                        <span>
My recommendation is to not add these icons in this PR.

2021-11-13 01:33 UTC, PeteCoward commented on src/Store.js
> +            setAddIstoriaError(state, payload) {
This breaks things!
Check your function naming

2021-11-13 01:33 UTC, PeteCoward requested changes
Check your console log for errors, both before adding new istoria, and after

2021-11-13 01:45 UTC, marobo commented on src/components/Istoria.vue
> +}
```suggestion
    .size_images {
        width: 100%;
    }
    .loader {
        position: absolute;
        display: flex;
        justify-content: space-evenly;
        align-items: center;
        text-align: center;
        top: 0px;
        left: 0px;
        width: 100%;
        height: 100%;
        z-index: 401;
        font-size: 32px;
        background-color: rgb(8 8 8 / 87%);
        color: var(--white);
    }
    .back-button {
        font-size: .7rem ;
        text-transform: uppercase;
        margin-bottom: 0.4rem;
        margin-right: 0.5rem;
        border-radius: 2rem;
        background: #fff;
        color: rgba(29,161,242,1.00);
        padding-right: 1rem;
        padding-left: 1rem;
        padding-top: 7px;
        padding-bottom: 4px;
        border: 1px solid rgba(29,161,242,1.00);
        letter-spacing: .8px;
        border-color: rgba(29,161,242,1.00);
        margin-top: 0.9rem;
        font-weight: bolder;
    }
```

2021-11-13 01:58 UTC, PeteCoward requested changes
Please make sure photos are never squashed

2021-12-11 02:04 UTC, PeteCoward commented
![Screenshot 2021-12-11 at 10 55 45](https://user-images.githubusercontent.com/1092029/145660201-c6dc085a-9daf-44a0-94ed-d4e383a4526d.png)
we should say "Adding comment..."

2021-12-11 02:39 UTC, PeteCoward approved these changes

2021-12-11 02:41 UTC, PeteCoward approved these changes

2021-12-11 02:44 UTC, marobo approved these changes

2021-12-11 04:25 UTC, merged

2021-12-17 12:23 UTC, joanico commented
@eraulo  After I add a comment, there is still having text in the input text field.
I think it should clear the input text after adding the comment to avoid duplicating the same meaning
 | -- | -- |
<img width="1434" alt="Screen Shot 2021-12-17 at 8 55 41 PM" src="https://user-images.githubusercontent.com/12932898/146543233-14d3b736-0978-4343-9108-c5b8f6420ef6.png">